name: API Drift

on:
  workflow_dispatch:
    inputs:
      vcc_token:
        description: 'vcc token'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Create VCC_TOKEN secret environment variable
        run: |
          VCC_TOKEN=$(jq -r '.inputs.vcc_token' $GITHUB_EVENT_PATH)
          echo "::add-mask::$VCC_TOKEN"
          echo VCC_TOKEN=$VCC_TOKEN >> $GITHUB_ENV

      - name: Install drift
        run: npm install -g @pactflow/drift

      - name: Authenticate drift
        run: drift auth login
        env:
          PACT_BROKER_BASE_URL: ${{ vars.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

      - name: Run Drift tests
        run: drift verify --server-url https://api.volvocars.com/connected-vehicle/v2 --test-files drift/drift.yaml
        env:
          VCC_API_KEY: ${{ secrets.VCC_API_KEY }}
          VCC_TOKEN: ${{ env.VCC_TOKEN }}
