name: API Drift

on:
  workflow_dispatch:
    inputs:
      vcc_token:
        description: 'vcc token'
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [
            ubuntu-latest,
            ubuntu-22.04-arm,
            windows-latest,
            windows-11-arm,
            macos-15-intel,
            macos-15
          ]      
    steps:
      - uses: actions/checkout@v6
      - name: Create VCC_TOKEN secret environment variable
        shell: bash
        run: |
          VCC_TOKEN=$(jq -r '.inputs.vcc_token' $GITHUB_EVENT_PATH)
          echo "::add-mask::$VCC_TOKEN"
          echo VCC_TOKEN=$VCC_TOKEN >> $GITHUB_ENV

      - name: Download and install Drift
        if: matrix.os != 'windows-11-arm'
        run: |
          npm install -g @pactflow/drift

      - name: Download and install Drift (win-arm64) # no native win-arm64 drift builds
        if: matrix.os == 'windows-11-arm'
        shell: pwsh
        run: |
          $driftPath = "$env:TEMP\drift"
          New-Item -ItemType Directory -Force -Path $driftPath | Out-Null
          Invoke-WebRequest -Uri "https://download.pactflow.io/drift/latest/windows-x86_64.tgz" -OutFile "$env:TEMP\drift.tgz"
          tar -xz -C $driftPath -f "$env:TEMP\drift.tgz"
          Add-Content $env:GITHUB_PATH $driftPath

      - name: Authenticate drift
        run: drift auth login
        env:
          PACT_BROKER_BASE_URL: ${{ vars.PACT_BROKER_BASE_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}

      - name: Install luarocks (windows)
        if: runner.os == 'Windows'
        run: choco install -y luarocks
      - name: Install luarocks (linux)
        if: runner.os == 'Linux'
        run: sudo apt install luarocks
      - name: Install luarocks (macos)
        if: runner.os == 'MacOS'
        run: brew install luarocks
      - name: Install luarocks deps
        if: runner.os == 'Linux' || matrix.os == 'macos-15-intel'
        run: |
          luarocks path
          sudo luarocks install dkjson
      - name: Install luarocks deps
        if: runner.os != 'Linux' && matrix.os != 'macos-15-intel'
        run: |
          luarocks path
          luarocks install dkjson

      - name: Run Drift tests
        shell: bash
        run: |
          eval $(luarocks path)
          drift verify --server-url https://api.volvocars.com/connected-vehicle/v2 --test-files drift/drift.yaml --log-level debug
        env:
          VCC_API_KEY: ${{ secrets.VCC_API_KEY }}
          VCC_TOKEN: ${{ env.VCC_TOKEN }}
